feat(nvim): use grealpath in tmux-sessionizer

diff --git a/bin/.local/scripts/tmux-sessionizer b/bin/.local/scripts/tmux-sessionizer
--- a/bin/.local/scripts/tmux-sessionizer
+++ b/bin/.local/scripts/tmux-sessionizer
@@ -2,6 +2,12 @@
 
 RESET='\e[0m'
 CYAN='\e[0;36m'
+RED='\e[1;31m'
+
+if ! command -v grealpath &> /dev/null; then
+  printf "${RED}[!]${RESET} grealpath not found, install coreutils (brew install coreutils)\n"
+  exit 1
+fi
 
 # Collect list of active sessions
 read -rd '' -a ACTIVE_SESSIONS_INFO <<< $(tmux list-sessions -F '#{session_name};#{session_path};#{session_activity}' -f '#{session_windows}' | sort -r -k 3)
@@ -11,7 +17,7 @@ ACTIVE_SESSIONS_PATHS=()
 # Add paths to ACTIVE_SESSIONS_PATHS, relative to home directory, sorted by recently used
 for i in "${!ACTIVE_SESSIONS_INFO[@]}"; do
   IFS=';' read -r -a SESSION_INFO <<< "${ACTIVE_SESSIONS_INFO[$i]}"
-  RELATIVE_PATH=$(realpath --relative-to ~ -- "${SESSION_INFO[1]}")
+  RELATIVE_PATH=$(grealpath --relative-to ~ -- "${SESSION_INFO[1]}")
 
   if [[ "${RELATIVE_PATH}" == "." ]]; then
     ACTIVE_SESSIONS_PATHS+=("~")
@@ -29,7 +35,7 @@ done
 
 # Collect list of all project paths under selected directories
 read -rd '' -a FIND_PATHS <<< $(find ~/work ~/projects ~/personal -mindepth 1 -maxdepth 1 -type d 2>/dev/null \
-  | xargs realpath --relative-to ~ \
+  | xargs grealpath --relative-to ~ \
   | sed -e 's/^/~\//'
 )
 
